### PR TITLE
fix npm start error

### PR DESCRIPTION
**Pull request by blackmatch**
I clone the origin repo, and then 'npm install', and then 'npm start', and then error cccured!  Need to run 'roadhog buildDll' bebofe 'roadhog server'.This PR fixes the error.

### CODE REVIEW

**Comment by Zuckjet** [comment]
thanks

**Comment by MinJieLiu** [comment]
@blackmatch Is this better?

```js
"scripts": {
  "start": "roadhog server",
  "build": "roadhog build",
  "build:dll": "roadhog buildDll",
  "postinstall": "npm run build:dll",
},
```

**Comment by blackmatch** [comment]
`postinstall ` means `Run AFTER the package is installed`. Maybe it's better. @MinJieLiu

**Comment by sorrycc** [comment]
> postinstall means Run AFTER the package is installed. Maybe it's better. @MinJieLiu

Agree.

**Pull request closed without merging**
